### ISSUE TITLE
Unable to compile against SVN 1.6

### ISSUE THREAD

**Issue by mrtimp** [aholmes/php-svn#1]
Hi there,

Trying compile to the latest master on a CentOS 6.4 x86_64 host with subversion 1.6.11 you hit the following errors:

/root/rpmbuild/BUILD/php-pecl-svn-2.0/svn-2.0/svn.c: At top level:
/root/rpmbuild/BUILD/php-pecl-svn-2.0/svn-2.0/svn.c:4100: error: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token

and

/root/rpmbuild/BUILD/php-pecl-svn-2.0/svn-2.0/svn.c:4196: error: ‘php_svn_status_receiver’ undeclared (first use in this function)
/root/rpmbuild/BUILD/php-pecl-svn-2.0/svn-2.0/svn.c:4196: error: (Each undeclared identifier is reported only once
/root/rpmbuild/BUILD/php-pecl-svn-2.0/svn-2.0/svn.c:4196: error: for each function it appears in.)

Does this module only work with SVN 1.7 or higher?

**Comment by aholmes** [comment]
Sorry for the delay. I've been away.

I had been building this module against SVN 1.7, and realized a few problems with SVN 1.6. I made some corrections once I noticed I was leaving 1.6 in the dust, but there are bound to be some issues with that SVN version.

Thanks for the bug report - I will try to get to this soon. If you're up for the challenge, here are some thoughts that might help get you rolling.

If you take a look at like 4100, you will see I am specifically checking for versions below 1.6. I likely didn't close this block, or the following, properly.

```
#if SVN_VER < 16
```

For the latter error, check out line 4253 for the use of php_svn_status_receiver https://github.com/aholmes/php-svn/blob/master/svn.c#L4253-L4283.

The definition for SVN 1.6 is here https://github.com/aholmes/php-svn/blob/master/svn.c#L4161-L4208.

Sorry, I don't really have any ideas for this one off the top of my head, except that I probably got some pre-processor directives wrong.
